name: Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:       # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Pacman Contribution Graph
        uses: Ileriayo/pacman-graphql-graph@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: HarmanB1
          output_path: output
